In [1]:
from pyGS.datastruct.scalefree2 import scalefree2
from pyGS.datastruct.Dataset import Dataset
from pyGS.datastruct.randomNet import randomNet
from pyGS.datastruct.stabilize import stabilize
from pyGS.datastruct.Network import Network	
##50sec to initially import

Building network: 100%|█████████▉| 493/495 [00:00<00:00, 13059.35it/s]

[[ 0. -1.  0. ...  0.  0.  0.]
 [-1.  0. -1. ...  0.  0.  0.]
 [ 0. -1.  0. ...  0. -1.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. -1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [3]:

Ne = Network()
import numpy as np
# Defining number of nodes
N = 10
# Defining the sparsity
S = 0.25
A = randomNet(N,S)-np.eye(N)
# A = stabilize(A,'iaa','high')
# Net = Ne.Network(A,'random')
# creator_setting = {'creator':'Nordlinglab_Justin'}
# Net.setname(Net,creator_setting)


In [4]:
%%time
N = int(50)
S = int(3)
import pyGS.datastruct as datastruct
# from pyGS.datastruct.scalefree2 import scalefree2
# from pyGS.datastruct.scalefree import scalefree

import scipy.sparse as sparse
A = scalefree2(N, S)
# A = stabilize(A,'iaa','low')
Net = Network(net=A)

Building network:  18%|█▊        | 657/3675 [00:00<00:00, 12366.64it/s]


AttributeError: 'numpy.ndarray' object has no attribute 'get'

In [ ]:
if A is None:
    print('A is None')

In [ ]:
import numpy as np
from scipy.linalg import svd
from scipy.stats import chi2
import matplotlib.pyplot as plt

# Assume Net.G is the static gain matrix and Net.network is the network adjacency matrix
# For this example, we create a dummy network and a gain matrix
N = 100  # Number of nodes
Net_G = np.random.normal(size=(N, 2*N))  # Static gain model
Net_network = np.random.rand(N, N) > 0.95  # Sparse network

# Create P matrix
P = -np.hstack([np.eye(N), np.eye(N)])

# Create data
X = np.dot(Net_G, P)  # Matrix multiplication

# Add noise to data
# Define signal-to-noise ratio
SNR = 0.1  # usually 1 is low, 0.1 is medium, 0.01 is high noise
s = svd(X, compute_uv=False)
stdE = s[-1] / (SNR * np.sqrt(chi2.ppf(0.99, df=np.prod(P.shape))))  # Using 99% confidence

# Estimate noise matrix
E = stdE * np.random.randn(*P.shape)

# Input noise matrix
F = np.zeros_like(P)

# Prepare data structure object
D = {
    'network': Net_network,
    'E': E,
    'F': F,
    'Y': X + E,  # noise-free gene expression + noise
    'P': P,
    'lambda': [stdE**2, 0],
    'cvY': stdE**2 * np.eye(N),
    'cvP': np.zeros((N, N)),
    'sdY': stdE * np.ones_like(P),
    'sdP': np.zeros_like(P)
}

# Placeholder for creating data object with data "D" and scale-free network "Net"
# Assuming we need to write a class or function `Dataset` and `Methods.lsco` to handle this
# This part is highly context-specific and would require implementing or using existing library functions

# Example placeholder functions and classes (implement these according to your actual needs)
class Dataset:
    def __init__(self, data, net):
        self.data = data
        self.net = net

    # Placeholder for a method that runs inference
    def run_inference(self, method, zeta):
        # Example inference code (simplified)
        return np.linalg.pinv(self.data['P']) @ self.data['Y'], zeta

# Initialize Dataset
data = Dataset(D, Net_network)

# Now we can run inference and benchmark it against our gold standard
zeta = np.logspace(-6, 0, 30)  # return 30 networks of full sparsity spectrum
inf_method = 'lsco'
Aest0, z0 = data.run_inference(inf_method, zeta)
Aest01 = Aest0[:, :, 25]  # Select network 25

# Display AUROC and max F1 score - placeholders for actual implementation
print("AUROC: Placeholder value")
print("Max F1 score: Placeholder value")

# The above Python code requires actual implementation of the Methods and analyse classes/methods.
